//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackPotAspApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceAfterWorkingHour
    {
        public int PriceAfterWorkingHourId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string cate { get; set; }
        public Nullable<long> rank { get; set; }
        public string name { get; set; }
        public string symbolCode { get; set; }
        public string code { get; set; }
        public Nullable<double> tradePrice { get; set; }
        public string change { get; set; }
        public Nullable<double> changePrice { get; set; }
        public Nullable<double> changeRate { get; set; }
        public Nullable<double> pricePerformance { get; set; }
        public Nullable<long> accTradeVolume { get; set; }
        public Nullable<long> accTradePrice { get; set; }
        public Nullable<double> regularHoursTradePrice { get; set; }
        public string regularHoursChange { get; set; }
        public Nullable<double> regularHoursChangePrice { get; set; }
        public Nullable<double> regularHoursChangeRate { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public string codeNum { get; set; }
    }
}
